"""adding visibility to workouts

Revision ID: 13ab4b6200f6
Revises: 55c6aaefd7d6
Create Date: 2025-11-23 20:57:27.761040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ab4b6200f6'
down_revision: Union[str, Sequence[str], None] = '55c6aaefd7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('visibility', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'visibility')
    # ### end Alembic commands ###
