"""added new table and fields to user table

Revision ID: 17825505648a
Revises: eb0fc5a4613c
Create Date: 2025-11-20 23:51:43.536345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17825505648a'
down_revision: Union[str, Sequence[str], None] = 'eb0fc5a4613c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_metrics', 'total_api_calls',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_metrics', 'total_api_calls',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
