"""added location info to users

Revision ID: 4f99c22df510
Revises: 8ab9f96880fd
Create Date: 2026-01-16 13:46:08.790686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f99c22df510'
down_revision: Union[str, Sequence[str], None] = '8ab9f96880fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_privacy', sa.String(), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('last_location_update', sa.DateTime(), nullable=True))
    op.alter_column('workouts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'last_location_update')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'profile_privacy')
    # ### end Alembic commands ###
