"""avg hear rate

Revision ID: 522bfaebad3a
Revises: c5fe3637adc6
Create Date: 2025-12-31 16:51:57.543565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522bfaebad3a'
down_revision: Union[str, Sequence[str], None] = 'c5fe3637adc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_daily', sa.Column('avg_heart_rate', sa.Float(), nullable=True))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('health_daily', 'avg_heart_rate')
    # ### end Alembic commands ###
