"""added push notification feature

Revision ID: 548da96d447c
Revises: 13ab4b6200f6
Create Date: 2025-11-23 23:02:55.682556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548da96d447c'
down_revision: Union[str, Sequence[str], None] = '13ab4b6200f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('push_token', sa.String(), nullable=True))
    op.alter_column('workouts', 'visibility',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'visibility',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'push_token')
    # ### end Alembic commands ###
