"""added new metric to app_metrics

Revision ID: 55c6aaefd7d6
Revises: ce4f256c4569
Create Date: 2025-11-21 21:58:14.884115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c6aaefd7d6'
down_revision: Union[str, Sequence[str], None] = 'ce4f256c4569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_metrics', sa.Column('rubbish_voice_logs', sa.Integer(), nullable=True))
    op.alter_column('app_metrics', 'total_api_calls',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_metrics', 'total_api_calls',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('app_metrics', 'rubbish_voice_logs')
    # ### end Alembic commands ###
