"""added nudge and spot features

Revision ID: c3cca0c6a9df
Revises: 13ab4b6200f6
Create Date: 2025-11-28 17:12:44.742609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3cca0c6a9df'
down_revision: Union[str, Sequence[str], None] = '13ab4b6200f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nudge_count', sa.Integer()))
    op.add_column('users', sa.Column('spot_count', sa.Integer()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spot_count')
    op.drop_column('users', 'nudge_count')
    # ### end Alembic commands ###
