"""added isadmin to table

Revision ID: c5fe3637adc6
Revises: c3cca0c6a9df
Create Date: 2025-11-30 15:42:57.469541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5fe3637adc6'
down_revision: Union[str, Sequence[str], None] = 'c3cca0c6a9df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('users', 'nudge_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'spot_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'spot_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'nudge_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
