"""added new metric to app_metrics

Revision ID: ce4f256c4569
Revises: 17825505648a
Create Date: 2025-11-21 21:41:05.266594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4f256c4569'
down_revision: Union[str, Sequence[str], None] = '17825505648a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_metrics', sa.Column('open_ai_calls', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_metrics', 'open_ai_calls')
    # ### end Alembic commands ###
