"""added pace_unit to the cardio sessions table

Revision ID: eb0fc5a4613c
Revises: 527700ed599c
Create Date: 2025-11-17 20:03:47.173739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0fc5a4613c'
down_revision: Union[str, Sequence[str], None] = '527700ed599c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardio_sessions', sa.Column('pace_unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cardio_sessions', 'pace_unit')
    # ### end Alembic commands ###
